# Generated by Django 3.1.4 on 2021-01-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0006_auto_20210105_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='blog_category',
        ),
    ]
