# Generated by Django 3.1 on 2021-01-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0007_auto_20210105_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cname', to='newblog.category'),
        ),
    ]
