# Generated by Django 3.1 on 2021-01-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0008_auto_20210106_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newblog.category'),
        ),
    ]
