# Generated by Django 3.1 on 2021-01-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0009_auto_20210106_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
